### ISSUE TITLE
Several issues when filtering list from long to shorter (or short to longer)

### ISSUE THREAD

**Issue by dehmer** [wellyshen/react-cool-virtual#248]
# Bug Report

## Describe the Bug

Displaying a short list (81 entries) after a long list (830 entries) skips all but two (or a few) entries of shorter list and introduces excess free space before items displayed. `resetScroll` is enabled and  `itemCount` managed as local state.
**This only happens when first (longer) list was scrolled down for a few pages.**

## How to Reproduce

Usage:

```
  const [itemCount, setItemCount] = React.useState(entries.length)
  const { outerRef, innerRef, items, scrollToItem } = useVirtual({
    itemCount,
    resetScroll: true
  })

  React.useEffect(() => {
    setItemCount(entries.length)
  }, [entries])

```
## CodeSandbox Link

I'm working on a CodeSandbox which reproduces this behavior. This will take a few days.

## Expected Behavior

Second (shorter) list is displayed with first entry at the top (provided `resetScroll` is working as intended).

## Screenshots

<img width="363" alt="Screenshot 2021-09-08 at 19 53 05" src="https://user-images.githubusercontent.com/322462/132562062-b49f1301-e9ce-4d51-8505-026202928872.png">

## Your Environment

* MacBook Pro (15-inch, 2017)
* macOS 11.5.2 (Big Sur)
* Electron 13.1.6

```
process.versions = {
  "node": "14.16.0",
  "v8": "9.1.269.36-electron.0",
  "uv": "1.40.0",
  "zlib": "1.2.11",
  "brotli": "1.0.9",
  "ares": "1.16.1",
  "modules": "89",
  "nghttp2": "1.41.0",
  "napi": "7",
  "llhttp": "2.1.3",
  "openssl": "1.1.1",
  "icu": "68.1",
  "unicode": "13.0",
  "electron": "13.1.6",
  "chrome": "91.0.4472.124"
}
```

## Additional Information

N/A

**Comment by wellyshen** [comment]
@dehmer I can't reproduce this issue. Waiting for the CodeSandbox.

**Comment by dehmer** [comment]
@wellyshen Check! 
In the existing CodeSandbox I can't reproduce it either. I'm going to try to mimic the real application as close as possible to get to the bottom of this. Hold tight until then.
Cheers, buddy!

**Comment by dehmer** [comment]
Here we go! Faster than anticipated: https://codesandbox.io/s/lively-fast-5834r
The only difference I'm aware of is `React.forwardRef()` on `IndexEntry`.

Steps:
1. In 800 rows list scroll down ~1/2 of the list or more
2. Switch over to 10 rows list
3. Only the last (2) entries of 10 rows list are displayed

<img width="831" alt="Screenshot 2021-09-09 at 07 55 30" src="https://user-images.githubusercontent.com/322462/132630979-d53c0d86-10fa-4307-8add-8a446e02c2fd.png">

**Comment by wellyshen** [comment]
@dehmer Thank you for the reproduced code, will investigate that soon. BTW, thanks for the donation of Syncpoint ❤️

**Comment by dehmer** [comment]
You're welcome! We have to thank you, and don't hurry. 
There is no rush on our side.

**Comment by wellyshen** [comment]
@dehmer This issue should be fixed in [v0.5.2](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.5.2), thank you mate.

**Comment by dehmer** [comment]
@wellyshen Looks good! Issue is gone and overshooting is no longer ocurring neither. Nice job!
Thanks for the fast response and quick fix!

**Comment by dehmer** [comment]
@wellyshen Sorry, overshooting still happens. I just removed the warning. Keeping the logic to detect and handle it for the time being.

**Comment by wellyshen** [comment]
@dehmer Yep, the fixing isn't related to that.

**Comment by dehmer** [comment]
Now I'm seeing a few other issues (possibly related):

1. Occasionally, going from big to small list, the following error is thrown (doesn't seem to impact correctness of list)
<img width="1063" alt="Screenshot 2021-09-10 at 08 08 28" src="https://user-images.githubusercontent.com/322462/132809765-e535d93e-f6ae-4cea-a6d2-80b7b93740e2.png">
<img width="954" alt="Screenshot 2021-09-10 at 08 27 14" src="https://user-images.githubusercontent.com/322462/132809785-e4961af1-2712-4635-8724-7046b9c02ee3.png">

2. Also occasionally (but different from 1), going from filtered to complete list, complete list is truncated to exactly the number of entries from filtered list. Getting out from this state through new filtering is difficult, but not impossible.

3. One time, excess free space was displayed below otherwise correct list.

It seems pretty hard to reproduce these error conditions. Also the behaviour is sort of non-deterministic (for now). I think there are one or more race conditions in play here.

I will try my best to figure out what's going on. In the meantime, maybe you have a few ideas about the root cause.

**Comment by dehmer** [comment]
OK. The first error can now be reproduced in the following CodeSandbox: https://codesandbox.io/s/cocky-microservice-45702

Steps A:
1. Type 'X' in filter field -> no matches; empty list (this is expected)
2. Clear filter -> boom!

Steps B (alternative)
1. Type 'sigacts' in filter field -> 8 matches; all matches displayed
2. Clear filter by cutting text at once (i.e. not deleting individual characters) -> boom!

**Comment by wellyshen** [comment]
@dehmer I know the root cause of the `undefined` parts that causes the app crash. Will fix them soon. Thank you!

**Comment by dehmer** [comment]
Thanks a lot! Take your time!
...Although I can't wait to put useVirtual() to production 😀

**Comment by wellyshen** [comment]
@dehmer The app crash and undefined `size` should be fixed in [v0.5.3](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.5.3). For the following issues, can you give me a reproduced CodeSandbox? Thank you.

2. Also occasionally (but different from 1), going from filtered to complete list, complete list is truncated to exactly the number of entries from filtered list. Getting out from this state through new filtering is difficult, but not impossible.

3. One time, excess free space was displayed below otherwise correct list.

**Comment by dehmer** [comment]
OK. I will verify the patch first 
If the issue 2 and 3 still apply, I try to come up with an updated CodeSandbox.
This might take a few days. I'm pretty busy doing nothing.

**Comment by wellyshen** [comment]
@dehmer I have noticed that the 2 and 3 still occur, will fix them soon. You can also update the CodeSandbox as well to make sure we are on the same page, thanks.

**Comment by dehmer** [comment]
Yes. I slightly modified https://codesandbox.io/s/cocky-microservice-45702

Try this to reproduce issue 2:
1. filter: type '4c'
2. filter: cut '4c'
3. scroll to list bottom with cursor down key
4. filter: paste '4c'
5. filter: cut '4c'
expected: list shows some 80 entries
actual: list shows only 7 entries

**Comment by wellyshen** [comment]
@dehmer Sorry for the late, these issues should be fixed in [v0.5.4](https://github.com/wellyshen/react-cool-virtual/releases/tag/v0.5.4), thank you mate.

**Comment by dehmer** [comment]
@wellyshen Thank you!
Looks good so far. We will test extensively in the coming days.
Fingers crossed! 🤞

**Comment by wellyshen** [comment]
@dehmer Thank you mate, let me know if there's an issue.
